### ISSUE TITLE
order of operations

### ISSUE THREAD

**Issue by karpathy** [bpesquet/pyfit#1]
https://github.com/bpesquet/pyfit/blob/df3bbf08bbdb34bb62d4e6f5a190c53f9c90dc97/pyfit/engine.py#L116

does one have to be careful here since `a - b != b - a`?

**Comment by bpesquet** [comment]
As I found out recently, `__rsub__()` is for the `other - my_object` cases (see [this SO answer](https://stackoverflow.com/a/3763895)).
So yes, `self` and `other`have to be switched.

Your solution for `-` and `/` operators is clever and more concise than mine. However, I like to have operators appear explicitly in the computation graph, so I'm going with explicitness here.

It's great to work in parallel and share ideas! i'm looking forward to seeing how micrograd evolves ;)

**Comment by karpathy** [comment]
Agree, it does pollute graphviz vis/tracing and makes it harder to map the graph onto what you actually wrote. I decided that I didn't consider the graphs to be the main product of the repo but the code and its length / scariness itself, so I went this way. Both are valid, tough call :). Thanks!
